# Generated by Django 4.0 on 2023-03-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Users',
        ),
    ]
